## Домашнее задание 2

## Задание

Дана страница с описанием **фильма-сказки «Не покидай...»** на сайте **КИНО-ТЕАТР.РУ**. Ссылка на [страницу](https://www.kino-teatr.ru/kino/movie/sov/4319/titr/) с перечнем ролей сохранена в переменной `titr`.

Если вдруг возникают проблемы с доступом (при парсинге выдается не исходный код страницы, а пустая страница с сообщением о попытках автоматического подключения к странице), можете воспользоваться запасной ссылкой `titr2`, это ссылка на копию страницы в репозитории Github, она точно открывается.

In [7]:
titr = "https://www.kino-teatr.ru/kino/movie/sov/4319/titr/"

In [8]:
# запасная
titr2 = "https://raw.githubusercontent.com/allatambov/WebScrape25/refs/heads/main/titr.html"

В задаче 1 *карточка* – это раздел страницы с фотографией, фамилией и именем актёра/актрисы, названием и кратким описанием роли. Пример карточки для первой роли:

![](https://github.com/allatambov/WebScrape25/blob/main/card-ex.png?raw=true)

## Немного мотивации от героев сказки

*И пример небольшого HTML со стилевыми настройками – внутри этой ячейки*

<html>
    <table>
        <tr>
            <td style="width:50%;background:white">
                <img src="https://github.com/allatambov/WebScrape25/blob/main/М1.png?raw=true" width="30%"/>
            </td>
            <td style="background:white">
                <p><b>Позитивная мотивация от Жака</b></p>
                <p>Мы с тобой – молодцы!</p>
             </td>
         </tr>
        <tr>
            <td style="width:50%">
                <img src="https://github.com/allatambov/WebScrape25/blob/main/М2.png?raw=true" width="30%"/>
            </td>
            <td>
                <p><b>Негативная мотивация от Оттилии</b></p>
                <p>Вы король или тряпка, в конце концов?!</p>
             </td>
         </tr>
    </table>
</html>

### Задача 1 (2 балла)

Используя возможности библиотек `requests` и `BeautifulSoup`, сохраните в список `act_info` информацию об актёрах (в «сыром» виде, в виде объектов `BeautifulSoup`), которая хранится на карточке актёра. Для определённости – вот пример первого элемента такого списка:

```
<div class="actor_details">
<div class="actor_film_descript" id="role_16801">
<div class="film_name"><a href="/kino/acter/w/sov/4484/bio/" itemprop="url" title="Лидия Федосеева-Шукшина"><strong itemprop="name">Лидия Федосеева-Шукшина</strong></a></div>
<div class="film_role">Королева Флора — <span class="film_main_role">главная роль</span></div>
<div class="film_role_descript">жена короля Теодора</div>
<div class="film_rating"><span id="role_rating_16801"></span></div>
</div>
<div class="actor_film_screens"><a href="/kino/movie/sov/4319/foto/a4484/1162854/" title="Лидия Федосеева-Шукшина"><img alt="Лидия Федосеева-Шукшина" class="actor_film_img" src="/acter/photo/4/8/4484/pv_1162854.jpg" title="Лидия Федосеева-Шукшина"/></a></div>
</div>
```

Выберите только элементы с индексами от 0 до 33 **включительно**, сохраните изменения в том же списке. Если информация сгружена правильно, это все актёры без учета актёров дубляжа и каскадёров. Их труд очень ценен, особенно с учётом некоторых деталей съёмок, но для последующих задач нужен рейтинг, а его для актёров за кадром на сайте нет.

In [9]:
### YOUR CODE HERE ###
import requests
from bs4 import BeautifulSoup

page = requests.get(titr)

soup = BeautifulSoup(page.text)

act_info = soup.find_all("div", class_="actor_details")
act_info = act_info[:34]

for i, tag in enumerate(act_info):
    print(f"\n\n--- Актер  #{i} ---\n")
    print(tag.prettify())

print(page.status_code, len(act_info))

--- Актер  #0 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_16801">
  <div class="film_name">
   <a href="/kino/acter/w/sov/4484/bio/" itemprop="url" title="Лидия Федосеева-Шукшина">
    <strong itemprop="name">
     Лидия Федосеева-Шукшина
    </strong>
   </a>
  </div>
  <div class="film_role">
   Королева Флора —
   <span class="film_main_role">
    главная роль
   </span>
  </div>
  <div class="film_role_descript">
   жена короля Теодора
  </div>
  <div class="film_rating">
   <span id="role_rating_16801">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a4484/1162854/" title="Лидия Федосеева-Шукшина">
   <img alt="Лидия Федосеева-Шукшина" class="actor_film_img" src="/acter/photo/4/8/4484/pv_1162854.jpg" title="Лидия Федосеева-Шукшина"/>
  </a>
 </div>
</div>



--- Актер  #1 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_16800">
  <div class="film_name">
   <a href="/kino/acter/m/sov/3035/bio/" itemprop="url" title="Вячеслав Невинный">
    <strong itemprop="name">
     Вячеслав Невинный
    </strong>
   </a>
  </div>
  <div class="film_role">
   Король Теодор —
   <span class="film_main_role">
    главная роль
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_16800">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a3035/324377/" title="Вячеслав Невинный">
   <img alt="Вячеслав Невинный" class="actor_film_img" src="/acter/photo/5/3/3035/pv_324377.jpg" title="Вячеслав Невинный"/>
  </a>
 </div>
</div>



--- Актер  #2 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_16803">
  <div class="film_name">
   <a href="/kino/acter/c/sov/2223/bio/" itemprop="url" title="Игорь Красавин">
    <strong itemprop="name">
     Игорь Красавин
    </strong>
   </a>
  </div>
  <div class="film_role">
   Патрик —
   <span class="film_main_role">
    главная роль
   </span>
  </div>
  <div class="film_role_descript">
   воспитанник королевы
  </div>
  <div class="film_rating">
   <span id="role_rating_16803">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a2223/114057/" title="Игорь Красавин">
   <img alt="Игорь Красавин" class="actor_film_img" src="/acter/photo/3/2/2223/pv_114057.jpg" title="Игорь Красавин"/>
  </a>
 </div>
</div>



--- Актер  #3 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_16802">
  <div class="film_name">
   <a href="/kino/acter/w/sov/792/bio/" itemprop="url" title="Варвара Владимирова">
    <strong itemprop="name">
     Варвара Владимирова
    </strong>
   </a>
  </div>
  <div class="film_role">
   Альбина
  </div>
  <div class="film_rating">
   <span id="role_rating_16802">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a792/321471/" title="Варвара Владимирова">
   <img alt="Варвара Владимирова" class="actor_film_img" src="/acter/photo/2/9/792/pv_321471.jpg" title="Варвара Владимирова"/>
  </a>
 </div>
</div>



--- Актер  #4 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_89473">
  <div class="film_name">
   <a href="/kino/acter/w/sov/3837/bio/" itemprop="url" title="Светлана Селезнёва">
    <strong itemprop="name">
     Светлана Селезнёва
    </strong>
   </a>
  </div>
  <div class="film_role">
   Марселла
  </div>
  <div class="film_role_descript">
   служанка
  </div>
  <div class="film_rating">
   <span id="role_rating_89473">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a3837/52038/" title="Светлана Селезнёва">
   <img alt="Светлана Селезнёва" class="actor_film_img" src="/acter/photo/7/3/3837/pv_52038.jpg" title="Светлана Селезнёва"/>
  </a>
 </div>
</div>



--- Актер  #5 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_124124">
  <div class="film_name">
   <a href="/kino/acter/w/sov/15116/bio/" itemprop="url" title="Регина Разума">
    <strong itemprop="name">
     Регина Разума
    </strong>
   </a>
  </div>
  <div class="film_role">
   Оттилия
  </div>
  <div class="film_role_descript">
   сестра королевы Флоры, тетка Альбины
  </div>
  <div class="film_rating">
   <span id="role_rating_124124">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a15116/324380/" title="Регина Разума">
   <img alt="Регина Разума" class="actor_film_img" src="/acter/photo/6/1/15116/pv_324380.jpg" title="Регина Разума"/>
  </a>
 </div>
</div>



--- Актер  #6 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_16804">
  <div class="film_name">
   <a href="/kino/acter/m/sov/4515/bio/" itemprop="url" title="Альберт Филозов">
    <strong itemprop="name">
     Альберт Филозов
    </strong>
   </a>
  </div>
  <div class="film_role">
   Канцлер граф Давиль
  </div>
  <div class="film_rating">
   <span id="role_rating_16804">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a4515/324378/" title="Альберт Филозов">
   <img alt="Альберт Филозов" class="actor_film_img" src="/acter/photo/5/1/4515/pv_324378.jpg" title="Альберт Филозов"/>
  </a>
 </div>
</div>



--- Актер  #7 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132138">
  <div class="film_name">
   <a href="/kino/acter/m/sov/17336/bio/" itemprop="url" title="Артём Тынкасов">
    <strong itemprop="name">
     Артём Тынкасов
    </strong>
   </a>
  </div>
  <div class="film_role">
   Пенапью
  </div>
  <div class="film_role_descript">
   принц государства Пенагония, сын короля Гедеона
  </div>
  <div class="film_rating">
   <span id="role_rating_132138">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a17336/263152/" title="Артём Тынкасов">
   <img alt="Артём Тынкасов" class="actor_film_img" src="/acter/photo/6/3/17336/pv_263152.jpg" title="Артём Тынкасов"/>
  </a>
 </div>
</div>



--- Актер  #8 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_56008">
  <div class="film_name">
   <a href="/kino/acter/w/sov/181/bio/" itemprop="url" title="Елена Антонова">
    <strong itemprop="name">
     Елена Антонова
    </strong>
   </a>
  </div>
  <div class="film_role">
   Марта Веснушка
  </div>
  <div class="film_role_descript">
   актриса бродячей труппы
  </div>
  <div class="film_rating">
   <span id="role_rating_56008">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a181/287657/" title="Елена Антонова">
   <img alt="Елена Антонова" class="actor_film_img" src="/acter/photo/1/8/181/pv_287657.jpg" title="Елена Антонова"/>
  </a>
 </div>
</div>



--- Актер  #9 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132139">
  <div class="film_name">
   <a href="/kino/acter/m/sov/17337/bio/" itemprop="url" title="Владимир Ставицкий">
    <strong itemprop="name">
     Владимир Ставицкий
    </strong>
   </a>
  </div>
  <div class="film_role">
   Жак Веснушка
  </div>
  <div class="film_role_descript">
   странствующий артист
  </div>
  <div class="film_rating">
   <span id="role_rating_132139">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a17337/263156/" title="Владимир Ставицкий">
   <img alt="Владимир Ставицкий" class="actor_film_img" src="/acter/photo/7/3/17337/pv_263156.jpg" title="Владимир Ставицкий"/>
  </a>
 </div>
</div>



--- Актер  #10 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_72744">
  <div class="film_name">
   <a href="/kino/acter/m/sov/3642/bio/" itemprop="url" title="Анатолий Рудаков">
    <strong itemprop="name">
     Анатолий Рудаков
    </strong>
   </a>
  </div>
  <div class="film_role">
   Удилак
  </div>
  <div class="film_role_descript">
   полковник, доверенное лицо короля Теодора
  </div>
  <div class="film_rating">
   <span id="role_rating_72744">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a3642/324379/" title="Анатолий Рудаков">
   <img alt="Анатолий Рудаков" class="actor_film_img" src="/acter/photo/2/4/3642/pv_324379.jpg" title="Анатолий Рудаков"/>
  </a>
 </div>
</div>



--- Актер  #11 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132140">
  <div class="film_name">
   <a href="/kino/acter/m/sov/17338/bio/" itemprop="url" title="Юрий Багинян">
    <strong itemprop="name">
     Юрий Багинян
    </strong>
   </a>
  </div>
  <div class="film_role">
   Лысый Лакей
  </div>
  <div class="film_role_descript">
   личный шпион Канцлера во дворце
  </div>
  <div class="film_rating">
   <span id="role_rating_132140">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #12 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_62460">
  <div class="film_name">
   <a href="/kino/acter/m/sov/1242/bio/" itemprop="url" title="Александр Денисов">
    <strong itemprop="name">
     Александр Денисов
    </strong>
   </a>
  </div>
  <div class="film_role">
   Разбойник
  </div>
  <div class="film_role_descript">
   лесной мачо, предводитель разбойников
  </div>
  <div class="film_rating">
   <span id="role_rating_62460">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #13 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132141">
  <div class="film_name">
   <a href="/kino/acter/m/sov/592/bio/" itemprop="url" title="Валентин Букин">
    <strong itemprop="name">
     Валентин Букин
    </strong>
   </a>
  </div>
  <div class="film_role">
   Хозяин таверны
  </div>
  <div class="film_role_descript">
   доносчик
  </div>
  <div class="film_rating">
   <span id="role_rating_132141">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #14 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_83813">
  <div class="film_name">
   <a href="/kino/acter/m/post/6057/bio/" itemprop="url" title="Анатолий Голуб">
    <strong itemprop="name">
     Анатолий Голуб
    </strong>
   </a>
  </div>
  <div class="film_rating">
   <span id="role_rating_83813">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #15 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132142">
  <div class="film_name">
   <strong itemprop="name">
    Саша Занько
   </strong>
  </div>
  <div class="film_role">
   Гиппократ
  </div>
  <div class="film_role_descript">
   сын трактирщика
  </div>
  <div class="film_rating">
   <span id="role_rating_83813">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #16 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_132143">
  <div class="film_name">
   <a href="/kino/acter/c/sov/17340/bio/" itemprop="url" title="Вика Яблонская">
    <strong itemprop="name">
     Вика Яблонская
    </strong>
   </a>
  </div>
  <div class="film_role">
   Ника
  </div>
  <div class="film_role_descript">
   маленькая девочка, "подружка" Пенапью.
  </div>
  <div class="film_rating">
   <span id="role_rating_132143">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #17 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_2030314">
  <div class="film_name">
   <a href="/kino/acter/m/sov/259878/bio/" itemprop="url" title="Андрей Баутенко">
    <strong itemprop="name">
     Андрей Баутенко
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_2030314">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #18 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973004">
  <div class="film_name">
   <strong itemprop="name">
    С. Гецингер
   </strong>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_2030314">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #19 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973001">
  <div class="film_name">
   <a href="/kino/acter/m/sov/233851/bio/" itemprop="url" title="Дмитрий Диджиокас">
    <strong itemprop="name">
     Дмитрий Диджиокас
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1973001">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #20 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973002">
  <div class="film_name">
   <a href="/kino/acter/m/sov/6781/bio/" itemprop="url" title="Владимир Зубенко">
    <strong itemprop="name">
     Владимир Зубенко
    </strong>
   </a>
  </div>
  <div class="film_role">
   музыкант
  </div>
  <div class="film_rating">
   <span id="role_rating_1973002">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #21 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973003">
  <div class="film_name">
   <a href="/kino/acter/m/sov/6637/bio/" itemprop="url" title="Владимир Корпусь">
    <strong itemprop="name">
     Владимир Корпусь
    </strong>
   </a>
  </div>
  <div class="film_role">
   жандарм
  </div>
  <div class="film_rating">
   <span id="role_rating_1973003">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #22 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1966145">
  <div class="film_name">
   <a href="/kino/acter/m/sov/244340/bio/" itemprop="url" title="Ивар Кумник">
    <strong itemprop="name">
     Ивар Кумник
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1966145">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #23 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973005">
  <div class="film_name">
   <a href="/kino/acter/w/sov/11752/bio/" itemprop="url" title="Анна Маланкина">
    <strong itemprop="name">
     Анна Маланкина
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1973005">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #24 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973000">
  <div class="film_name">
   <a href="/kino/acter/m/post/8156/bio/" itemprop="url" title="Валерий Мороз">
    <strong itemprop="name">
     Валерий Мороз
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1973000">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #25 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_160325">
  <div class="film_name">
   <a href="/kino/director/sov/22358/bio/" itemprop="url" title="Леонид Нечаев">
    <strong itemprop="name">
     Леонид Нечаев
    </strong>
   </a>
  </div>
  <div class="film_role">
   точильщик ножей
  </div>
  <div class="film_rating">
   <span id="role_rating_160325">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
  <a href="/kino/movie/sov/4319/foto/a22358/324376/" title="Леонид Нечаев">
   <img alt="Леонид Нечаев" class="actor_film_img" src="/acter/photo/8/5/22358/pv_324376.jpg" title="Леонид Нечаев"/>
  </a>
 </div>
</div>



--- Актер  #26 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973006">
  <div class="film_name">
   <strong itemprop="name">
    И. Окал
   </strong>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_160325">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #27 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1928641">
  <div class="film_name">
   <a href="/kino/acter/w/sov/12874/bio/" itemprop="url" title="Анна Портная">
    <strong itemprop="name">
     Анна Портная
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1928641">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #28 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973007">
  <div class="film_name">
   <a href="/kino/acter/bitpart/m/sov/237131/bio/" itemprop="url" title="Ростислав Рахт">
    <strong itemprop="name">
     Ростислав Рахт
    </strong>
   </a>
  </div>
  <div class="film_role">
   шарманщик с попугаем
  </div>
  <div class="film_role_descript">
   озвучил Игорь Ясулович
  </div>
  <div class="film_rating">
   <span id="role_rating_1973007">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #29 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973009">
  <div class="film_name">
   <strong itemprop="name">
    В. Славуник
   </strong>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1973007">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #30 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973008">
  <div class="film_name">
   <a href="/kino/acter/m/sov/34268/works/" itemprop="url" title="Юрий Шульга">
    <strong itemprop="name">
     Юрий Шульга
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_rating">
   <span id="role_rating_1973008">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #31 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_2088754">
  <div class="film_name">
   <a href="/kino/acter/m/sov/5545/bio/" itemprop="url" title="Александр Макарцев">
    <strong itemprop="name">
     Александр Макарцев
    </strong>
   </a>
  </div>
  <div class="film_role">
   музыкант
  </div>
  <div class="film_rating">
   <span id="role_rating_2088754">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #32 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973010">
  <div class="film_name">
   <a href="/kino/acter/m/sov/974/bio/" itemprop="url" title="Евгений Герчаков">
    <strong itemprop="name">
     Евгений Герчаков
    </strong>
   </a>
  </div>
  <div class="film_role">
   <span class="film_episode_role">
    эпизод
   </span>
  </div>
  <div class="film_role_descript">
   (нет в титрах)
  </div>
  <div class="film_rating">
   <span id="role_rating_1973010">
   </span>
  </div>
 </div>
 <div class="actor_film_screens">
 </div>
</div>



--- Актер  #33 ---

<div class="actor_details">
 <div class="actor_film_descript" id="role_1973011">
  <div class="film_name">
   <a href="/kino/acter/m/sov/1333/bio/" itemprop="url" title="Сергей Дрейден">
    <strong itemprop="name">
     Сергей Дрейден
    </strong>
   </a>
  </div>
  <div class="film_role">

### Задача 2 (4 балла)

Из каждого элемента списка `act_info` из предыдущей задачи извлеките следующую информацию:

* id актёра (`role_16801` в примере выше);
* ФИО актёра (`Лидия Федосеева-Шукшина` в примере выше);
* ссылка на страницу актёра (`/kino/acter/w/sov/4484/bio/` в примере выше, пустая строка, если ссылки нет);
* роль (`Королева Флора — главная роль` в примере выше, пустая строка, если название роли не найдено).

**Подсказка:** если название роли не найдено, используйте конструкцию `try-except`, чтобы в случае ошибки сохранять просто пустую строку. То же относится и к ссылке (можно написать ещё один `try-except`). Можете посмотреть на [пример](https://github.com/allatambov/WebScrape25/blob/main/try-except-example.ipynb), который натолкнёт на мысль, как эту конструкцию использовать в данном случае. В крайнем случае можете использовать обычную конструкцию `if-else` и проверять, результат поиска по тэгу `None` или нет.

В результате должен получиться список списков такого вида (даны первые два элемента и элементы с пустой строкой для примера):

```
[['role_16801', 'Лидия Федосеева-Шукшина', '/kino/acter/w/sov/4484/bio/',
'Королева Флора — главная роль'],
['role_16800', 'Вячеслав Невинный', 'kino/acter/m/sov/3035/bio/',
'Король Теодор — главная роль'],
...,
['role_83813', 'Анатолий Голуб', '/kino/acter/m/post/6057/bio/', ''],
['role_132142', 'Саша Занько', '', 'Гиппократ'],
...]
```

**Уточнение.** Вы можете решать задачу любым способом, главное, получить список нужного вида. Можно обойтись одним циклом, а можно написать функцию для получения списка с информацией по одному актёру, а дальше применить её ко всем элементам списка `act_info`.

In [10]:
### YOUR CODE HERE ###
def parse_actor(card):
    # id роли
    try:
        role_id = card.find("div", class_="actor_film_descript")["id"]
    except Exception:
        role_id = ""

    # ФИО
    try:
        name = card.find("strong", attrs={"itemprop": "name"}).get_text(strip=True)
    except Exception:
        name = ""

    # ссылка
    try:
        link = card.find("div", class_="film_name").find("a")["href"]
    except Exception:
        link = ""

    # роль
    try:
        role = card.find("div", class_="film_role").get_text(" ", strip=True)
    except Exception:
        role = ""

    return [role_id, name, link, role]

actors_data = [parse_actor(card) for card in act_info]

print(f"Статус ответаe: {page.status_code}")
print(f"Количество актеров в списке: {len(actors_data)}\n")

for item in actors_data:
    print(item)

Статус ответаe: 200
Количество актеров в списке: 34

['role_16801', 'Лидия Федосеева-Шукшина', '/kino/acter/w/sov/4484/bio/', 'Королева Флора — главная роль']
['role_16800', 'Вячеслав Невинный', '/kino/acter/m/sov/3035/bio/', 'Король Теодор — главная роль']
['role_16803', 'Игорь Красавин', '/kino/acter/c/sov/2223/bio/', 'Патрик — главная роль']
['role_16802', 'Варвара Владимирова', '/kino/acter/w/sov/792/bio/', 'Альбина']
['role_89473', 'Светлана Селезнёва', '/kino/acter/w/sov/3837/bio/', 'Марселла']
['role_124124', 'Регина Разума', '/kino/acter/w/sov/15116/bio/', 'Оттилия']
['role_16804', 'Альберт Филозов', '/kino/acter/m/sov/4515/bio/', 'Канцлер граф Давиль']
['role_132138', 'Артём Тынкасов', '/kino/acter/m/sov/17336/bio/', 'Пенапью']
['role_56008', 'Елена Антонова', '/kino/acter/w/sov/181/bio/', 'Марта Веснушка']
['role_132139', 'Владимир Ставицкий', '/kino/acter/m/sov/17337/bio/', 'Жак Веснушка']
['role_72744', 'Анатолий Рудаков', '/kino/acter/m/sov/3642/bio/', 'Удилак']
['role_132140', 'Юрий Багинян', '/kino/acter/m/sov/17338/bio/', 'Лысый Лакей']
['role_62460', 'Александр Денисов', '/kino/acter/m/sov/1242/bio/', 'Разбойник']
['role_132141', 'Валентин Букин', '/kino/acter/m/sov/592/bio/', 'Хозяин таверны']
['role_83813', 'Анатолий Голуб', '/kino/acter/m/post/6057/bio/', '']
['role_132142', 'Саша Занько', '', 'Гиппократ']
['role_132143', 'Вика Яблонская', '/kino/acter/c/sov/17340/bio/', 'Ника']
['role_2030314', 'Андрей Баутенко', '/kino/acter/m/sov/259878/bio/', 'эпизод']
['role_1973004', 'С. Гецингер', '', 'эпизод']
['role_1973001', 'Дмитрий Диджиокас', '/kino/acter/m/sov/233851/bio/', 'эпизод']
['role_1973002', 'Владимир Зубенко', '/kino/acter/m/sov/6781/bio/', 'музыкант']
['role_1973003', 'Владимир Корпусь', '/kino/acter/m/sov/6637/bio/', 'жандарм']
['role_1966145', 'Ивар Кумник', '/kino/acter/m/sov/244340/bio/', 'эпизод']
['role_1973005', 'Анна Маланкина', '/kino/acter/w/sov/11752/bio/', 'эпизод']
['role_1973000', 'Валерий Мороз', '/kino/acter/m/post/8156/bio/', 'эпизод']
['role_160325', 'Леонид Нечаев', '/kino/director/sov/22358/bio/', 'точильщик ножей']
['role_1973006', 'И. Окал', '', 'эпизод']
['role_1928641', 'Анна Портная', '/kino/acter/w/sov/12874/bio/', 'эпизод']
['role_1973007', 'Ростислав Рахт', '/kino/acter/bitpart/m/sov/237131/bio/', 'шарманщик с попугаем']
['role_1973009', 'В. Славуник', '', 'эпизод']
['role_1973008', 'Юрий Шульга', '/kino/acter/m/sov/34268/works/', 'эпизод']
['role_2088754', 'Александр Макарцев', '/kino/acter/m/sov/5545/bio/', 'музыкант']
['role_1973010', 'Евгений Герчаков', '/kino/acter/m/sov/974/bio/', 'эпизод']
['role_1973011', 'Сергей Дрейден', '/kino/acter/m/sov/1333/bio/', 'эпизод']

### Задача 3 (1 балл)

Преобразуйте полученный список списков в датафрейм `main`, присвойте столбцам названия `id`, `name`, `link`, `role`.

In [11]:
### YOUR CODE HERE ###
import pandas as pd

main = pd.DataFrame(actors_data, columns=["id", "name", "link", "role"])
main

,id,name,link,role
0,role_16801,Лидия Федосеева-Шукшина,/kino/acter/w/sov/4484/bio/,Королева Флора — главная роль
1,role_16800,Вячеслав Невинный,/kino/acter/m/sov/3035/bio/,Король Теодор — главная роль
2,role_16803,Игорь Красавин,/kino/acter/c/sov/2223/bio/,Патрик — главная роль
3,role_16802,Варвара Владимирова,/kino/acter/w/sov/792/bio/,Альбина
4,role_89473,Светлана Селезнёва,/kino/acter/w/sov/3837/bio/,Марселла
5,role_124124,Регина Разума,/kino/acter/w/sov/15116/bio/,Оттилия
6,role_16804,Альберт Филозов,/kino/acter/m/sov/4515/bio/,Канцлер граф Давиль
7,role_132138,Артём Тынкасов,/kino/acter/m/sov/17336/bio/,Пенапью
8,role_56008,Елена Антонова,/kino/acter/w/sov/181/bio/,Марта Веснушка
9,role_132139,Владимир Ставицкий,/kino/acter/m/sov/17337/bio/,Жак Веснушка
10,role_72744,Анатолий Рудаков,/kino/acter/m/sov/3642/bio/,Удилак
11,role_132140,Юрий Багинян,/kino/acter/m/sov/17338/bio/,Лысый Лакей
12,role_62460,Александр Денисов,/kino/acter/m/sov/1242/bio/,Разбойник
13,role_132141,Валентин Букин,/kino/acter/m/sov/592/bio/,Хозяин таверны
14,role_83813,Анатолий Голуб,/kino/acter/m/post/6057/bio/,
15,role_132142,Саша Занько,,Гиппократ
16,role_132143,Вика Яблонская,/kino/acter/c/sov/17340/bio/,Ника
17,role_2030314,Андрей Баутенко,/kino/acter/m/sov/259878/bio/,эпизод
18,role_1973004,С. Гецингер,,эпизод
19,role_1973001,Дмитрий Диджиокас,/kino/acter/m/sov/233851/bio/,эпизод
20,role_1973002,Владимир Зубенко,/kino/acter/m/sov/6781/bio/,музыкант
21,role_1973003,Владимир Корпусь,/kino/acter/m/sov/6637/bio/,жандарм
22,role_1966145,Ивар Кумник,/kino/acter/m/sov/244340/bio/,эпизод
23,role_1973005,Анна Маланкина,/kino/acter/w/sov/11752/bio/,эпизод
24,role_1973000,Валерий Мороз,/kino/acter/m/post/8156/bio/,эпизод
25,role_160325,Леонид Нечаев,/kino/director/sov/22358/bio/,точильщик ножей
26,role_1973006,И. Окал,,эпизод
27,role_1928641,Анна Портная,/kino/acter/w/sov/12874/bio/,эпизод
28,role_1973007,Ростислав Рахт,/kino/acter/bitpart/m/sov/237131/bio/,шарманщик с попугаем
29,role_1973009,В. Славуник,,эпизод
30,role_1973008,Юрий Шульга,/kino/acter/m/sov/34268/works/,эпизод
31,role_2088754,Александр Макарцев,/kino/acter/m/sov/5545/bio/,музыкант
32,role_1973010,Евгений Герчаков,/kino/acter/m/sov/974/bio/,эпизод
33,role_1973011,Сергей Дрейден,/kino/acter/m/sov/1333/bio/,эпизод

### Задача 4 (1 балл)

Дан список словарей, где каждый словарь содержит число лайков и дизлайков, поставленных актёрам зарегистрированными пользователями сайта (просто забрать их из исходного кода не получится, значения обновляются динамически, это возможно, но сложно, обсудим позже на занятии):

In [12]:
N = [{"id":"role_160325", "plus":"55", "minus":"2"},
     {"id":"role_1928641", "plus":"33", "minus":"1"},
     {"id":"role_1966145", "plus":"29", "minus":"1"},
     {"id":"role_1973000", "plus":"30", "minus":"1"},
     {"id":"role_1973001", "plus":"30", "minus":"1"},
     {"id":"role_1973002", "plus":"31", "minus":"0"},
     {"id":"role_1973003", "plus":"30", "minus":"1"},
     {"id":"role_1973005", "plus":"30", "minus":"2"},
     {"id":"role_1973007", "plus":"33", "minus":"1"},
     {"id":"role_1973008", "plus":"28", "minus":"1"},
     {"id":"role_1973010", "plus":"38", "minus":"7"},
     {"id":"role_1973011", "plus":"49", "minus":"3"},
     {"id":"role_2088754", "plus":"35", "minus":"2"},
     {"id":"role_16800", "plus":"173", "minus":"4"},
     {"id":"role_16801", "plus":"119", "minus":"28"},
     {"id":"role_16803", "plus":"136", "minus":"12"},
     {"id":"role_16802", "plus":"158", "minus":"11"},
     {"id":"role_16804", "plus":"150", "minus":"6"},
     {"id":"role_56008", "plus":"112", "minus":"10"},
     {"id":"role_62460", "plus":"112", "minus":"4"},
     {"id":"role_72744", "plus":"132", "minus":"3"},
     {"id":"role_83813", "plus":"49", "minus":"3"},
     {"id":"role_89473", "plus":"109", "minus":"22"},
     {"id":"role_124124", "plus":"138", "minus":"7"},
     {"id":"role_132138", "plus":"143", "minus":"3"},
     {"id":"role_132139", "plus":"124", "minus":"5"},
     {"id":"role_132140", "plus":"86", "minus":"3"},
     {"id":"role_132141", "plus":"79", "minus":"6"}]

Список словарей, как и список списков, можно превратить в датафрейм (супер-полезный факт, запомните, пригодится для преобразования выгруженной информации в привычный вид):

In [13]:
import pandas as pd
numbers = pd.DataFrame(N)

Измените тип столбцов `plus` и `minus` на *integer* (тип `int`) (вспомните пример из практикума со сложностью новости). Пока это столбцы с текстовыми значениями, что не позволит нам посчитать рейтинг – вычесть число дизлайков из числа лайков.

In [14]:
### YOUR CODE HERE ###
numbers['plus'] = numbers['plus'].apply(int)
numbers['minus'] = numbers['minus'].apply(int)
numbers.dtypes

id       object
plus      int64
minus     int64
dtype: object

Добавьте в датафрейм `numbers` столбец `rating`, который представляет собой рейтинг актёра, вычисляемый как разность между числом лайков и дизлайков.

In [15]:
### YOUR CODE HERE ###
numbers["rating"] = numbers["plus"] - numbers["minus"]
numbers.head()
numbers

              id  plus  minus  rating
0    role_160325    55      2      53
1   role_1928641    33      1      32
2   role_1966145    29      1      28
3   role_1973000    30      1      29
4   role_1973001    30      1      29
5   role_1973002    31      0      31
6   role_1973003    30      1      29
7   role_1973005    30      2      28
8   role_1973007    33      1      32
9   role_1973008    28      1      27
10  role_1973010    38      7      31
11  role_1973011    49      3      46
12  role_2088754    35      2      33
13    role_16800   173      4     169
14    role_16801   119     28      91
15    role_16803   136     12     124
16    role_16802   158     11     147
17    role_16804   150      6     144
18    role_56008   112     10     102
19    role_62460   112      4     108
20    role_72744   132      3     129
21    role_83813    49      3      46
22    role_89473   109     22      87
23   role_124124   138      7     131
24   role_132138   143      3     140
25   role_132139   124      5     119
26   role_132140    86      3      83
27   role_132141    79      6      73

Объединим датафреймы `main` и `numbers` по id актёров в датафрейм `final` (если в задаче 3 получился корректный столбец `id` с идентификаторами актёров, код ниже должен сработать):

In [16]:
# метод .merge(),
# столбец с id у датафреймов общий

final = main.merge(numbers, on = "id")

Отсортируем строки в датафрейме `final` по убыванию рейтинга (если в этой задаче получился корректный столбец `rating`, код ниже должен сработать) и сохраним изменения:

In [17]:
final = final.sort_values("rating", ascending = False)
final

,id,name,link,role,plus,minus,rating
1,role_16800,Вячеслав Невинный,/kino/acter/m/sov/3035/bio/,Король Теодор — главная роль,173,4,169
3,role_16802,Варвара Владимирова,/kino/acter/w/sov/792/bio/,Альбина,158,11,147
6,role_16804,Альберт Филозов,/kino/acter/m/sov/4515/bio/,Канцлер граф Давиль,150,6,144
7,role_132138,Артём Тынкасов,/kino/acter/m/sov/17336/bio/,Пенапью,143,3,140
5,role_124124,Регина Разума,/kino/acter/w/sov/15116/bio/,Оттилия,138,7,131
10,role_72744,Анатолий Рудаков,/kino/acter/m/sov/3642/bio/,Удилак,132,3,129
2,role_16803,Игорь Красавин,/kino/acter/c/sov/2223/bio/,Патрик — главная роль,136,12,124
9,role_132139,Владимир Ставицкий,/kino/acter/m/sov/17337/bio/,Жак Веснушка,124,5,119
12,role_62460,Александр Денисов,/kino/acter/m/sov/1242/bio/,Разбойник,112,4,108
8,role_56008,Елена Антонова,/kino/acter/w/sov/181/bio/,Марта Веснушка,112,10,102
0,role_16801,Лидия Федосеева-Шукшина,/kino/acter/w/sov/4484/bio/,Королева Флора — главная роль,119,28,91
4,role_89473,Светлана Селезнёва,/kino/acter/w/sov/3837/bio/,Марселла,109,22,87
11,role_132140,Юрий Багинян,/kino/acter/m/sov/17338/bio/,Лысый Лакей,86,3,83
13,role_132141,Валентин Букин,/kino/acter/m/sov/592/bio/,Хозяин таверны,79,6,73
21,role_160325,Леонид Нечаев,/kino/director/sov/22358/bio/,точильщик ножей,55,2,53
14,role_83813,Анатолий Голуб,/kino/acter/m/post/6057/bio/,,49,3,46
27,role_1973011,Сергей Дрейден,/kino/acter/m/sov/1333/bio/,эпизод,49,3,46
25,role_2088754,Александр Макарцев,/kino/acter/m/sov/5545/bio/,музыкант,35,2,33
22,role_1928641,Анна Портная,/kino/acter/w/sov/12874/bio/,эпизод,33,1,32
23,role_1973007,Ростислав Рахт,/kino/acter/bitpart/m/sov/237131/bio/,шарманщик с попугаем,33,1,32
16,role_1973002,Владимир Зубенко,/kino/acter/m/sov/6781/bio/,музыкант,31,0,31
26,role_1973010,Евгений Герчаков,/kino/acter/m/sov/974/bio/,эпизод,38,7,31
17,role_1973003,Владимир Корпусь,/kino/acter/m/sov/6637/bio/,жандарм,30,1,29
15,role_1973001,Дмитрий Диджиокас,/kino/acter/m/sov/233851/bio/,эпизод,30,1,29
20,role_1973000,Валерий Мороз,/kino/acter/m/post/8156/bio/,эпизод,30,1,29
18,role_1966145,Ивар Кумник,/kino/acter/m/sov/244340/bio/,эпизод,29,1,28
19,role_1973005,Анна Маланкина,/kino/acter/w/sov/11752/bio/,эпизод,30,2,28
24,role_1973008,Юрий Шульга,/kino/acter/m/sov/34268/works/,эпизод,28,1,27

Сейчас в `final` сохранены относительные ссылки, которые начинаются не с `https`. Для выполнения последней задачи добавим столбец с полной ссылкой на страницу актёра. Для этого доклеим в начало каждой ссылки в столбце `link` ссылку на главную страница сайта:

In [18]:
# ко всем ячейкам в столбце link применяем lambda-функцию,
# которая принимает на вход текст в ячейке (x),
# приклеивает к нему ссылку с https в начале
# и возвращает полную ссылку, которую мы сохраняем в новый столбец full_link

final["full_link"] = final["link"].apply(lambda x: "https://www.kino-teatr.ru" + x)
final

,id,name,link,role,plus,minus,rating,full_link
1,role_16800,Вячеслав Невинный,/kino/acter/m/sov/3035/bio/,Король Теодор — главная роль,173,4,169,https://www.kino-teatr.ru/kino/acter/m/sov/303...
3,role_16802,Варвара Владимирова,/kino/acter/w/sov/792/bio/,Альбина,158,11,147,https://www.kino-teatr.ru/kino/acter/w/sov/792...
6,role_16804,Альберт Филозов,/kino/acter/m/sov/4515/bio/,Канцлер граф Давиль,150,6,144,https://www.kino-teatr.ru/kino/acter/m/sov/451...
7,role_132138,Артём Тынкасов,/kino/acter/m/sov/17336/bio/,Пенапью,143,3,140,https://www.kino-teatr.ru/kino/acter/m/sov/173...
5,role_124124,Регина Разума,/kino/acter/w/sov/15116/bio/,Оттилия,138,7,131,https://www.kino-teatr.ru/kino/acter/w/sov/151...
10,role_72744,Анатолий Рудаков,/kino/acter/m/sov/3642/bio/,Удилак,132,3,129,https://www.kino-teatr.ru/kino/acter/m/sov/364...
2,role_16803,Игорь Красавин,/kino/acter/c/sov/2223/bio/,Патрик — главная роль,136,12,124,https://www.kino-teatr.ru/kino/acter/c/sov/222...
9,role_132139,Владимир Ставицкий,/kino/acter/m/sov/17337/bio/,Жак Веснушка,124,5,119,https://www.kino-teatr.ru/kino/acter/m/sov/173...
12,role_62460,Александр Денисов,/kino/acter/m/sov/1242/bio/,Разбойник,112,4,108,https://www.kino-teatr.ru/kino/acter/m/sov/124...
8,role_56008,Елена Антонова,/kino/acter/w/sov/181/bio/,Марта Веснушка,112,10,102,https://www.kino-teatr.ru/kino/acter/w/sov/181...
0,role_16801,Лидия Федосеева-Шукшина,/kino/acter/w/sov/4484/bio/,Королева Флора — главная роль,119,28,91,https://www.kino-teatr.ru/kino/acter/w/sov/448...
4,role_89473,Светлана Селезнёва,/kino/acter/w/sov/3837/bio/,Марселла,109,22,87,https://www.kino-teatr.ru/kino/acter/w/sov/383...
11,role_132140,Юрий Багинян,/kino/acter/m/sov/17338/bio/,Лысый Лакей,86,3,83,https://www.kino-teatr.ru/kino/acter/m/sov/173...
13,role_132141,Валентин Букин,/kino/acter/m/sov/592/bio/,Хозяин таверны,79,6,73,https://www.kino-teatr.ru/kino/acter/m/sov/592...
21,role_160325,Леонид Нечаев,/kino/director/sov/22358/bio/,точильщик ножей,55,2,53,https://www.kino-teatr.ru/kino/director/sov/22...
14,role_83813,Анатолий Голуб,/kino/acter/m/post/6057/bio/,,49,3,46,https://www.kino-teatr.ru/kino/acter/m/post/60...
27,role_1973011,Сергей Дрейден,/kino/acter/m/sov/1333/bio/,эпизод,49,3,46,https://www.kino-teatr.ru/kino/acter/m/sov/133...
25,role_2088754,Александр Макарцев,/kino/acter/m/sov/5545/bio/,музыкант,35,2,33,https://www.kino-teatr.ru/kino/acter/m/sov/554...
22,role_1928641,Анна Портная,/kino/acter/w/sov/12874/bio/,эпизод,33,1,32,https://www.kino-teatr.ru/kino/acter/w/sov/128...
23,role_1973007,Ростислав Рахт,/kino/acter/bitpart/m/sov/237131/bio/,шарманщик с попугаем,33,1,32,https://www.kino-teatr.ru/kino/acter/bitpart/m...
16,role_1973002,Владимир Зубенко,/kino/acter/m/sov/6781/bio/,музыкант,31,0,31,https://www.kino-teatr.ru/kino/acter/m/sov/678...
26,role_1973010,Евгений Герчаков,/kino/acter/m/sov/974/bio/,эпизод,38,7,31,https://www.kino-teatr.ru/kino/acter/m/sov/974...
17,role_1973003,Владимир Корпусь,/kino/acter/m/sov/6637/bio/,жандарм,30,1,29,https://www.kino-teatr.ru/kino/acter/m/sov/663...
15,role_1973001,Дмитрий Диджиокас,/kino/acter/m/sov/233851/bio/,эпизод,30,1,29,https://www.kino-teatr.ru/kino/acter/m/sov/233...
20,role_1973000,Валерий Мороз,/kino/acter/m/post/8156/bio/,эпизод,30,1,29,https://www.kino-teatr.ru/kino/acter/m/post/81...
18,role_1966145,Ивар Кумник,/kino/acter/m/sov/244340/bio/,эпизод,29,1,28,https://www.kino-teatr.ru/kino/acter/m/sov/244...
19,role_1973005,Анна Маланкина,/kino/acter/w/sov/11752/bio/,эпизод,30,2,28,https://www.kino-teatr.ru/kino/acter/w/sov/117...
24,role_1973008,Юрий Шульга,/kino/acter/m/sov/34268/works/,эпизод,28,1,27,https://www.kino-teatr.ru/kino/acter/m/sov/342...

### Задача 5 (2 балла)

Дан список с цитатами героев (местами с сокращениями):

In [19]:
L1 = [("Что-то написано... Ничего не понятно. Вот жалко.", "Марселла"),
      ("Я падаю. Держите меня!", "Альбина"),
      ("Ради гуманности...помогите!", "Пенапью"),
      ("Мы что-то не поняли... Вы... издеваетесь?", "Жак"),
      ("И не судите меня строго, я сегодня как пьяный.", "Патрик"),
      ("Это, конечно, очень смешно, но это уже было.", "Оттилия"),
      ("Разве такого озорства требует моя натура?", "Теодор"),
      ("Почему-то мне кажется, что в летнем замке на озёрах тебе было бы здоровее и спокойнее.",
       "Флора"),
      ("Ещё немного, Ваше величество, и вы вникните!", "Давиль"),
      ("Ты гений!", "Марта")
]

for phrase, name in L1:
    print(f"{phrase} ({name})")

Что-то написано... Ничего не понятно. Вот жалко. (Марселла)
Я падаю. Держите меня! (Альбина)
Ради гуманности...помогите! (Пенапью)
Мы что-то не поняли... Вы... издеваетесь? (Жак)
И не судите меня строго, я сегодня как пьяный. (Патрик)
Это, конечно, очень смешно, но это уже было. (Оттилия)
Разве такого озорства требует моя натура? (Теодор)
Почему-то мне кажется, что в летнем замке на озёрах тебе было бы здоровее и спокойнее. (Флора)
Ещё немного, Ваше величество, и вы вникните! (Давиль)
Ты гений! (Марта)

Выберите цитату из списка, которая больше всего похожа на фразу, которую вы могли бы произнести себе при выполнении этого ДЗ :)

Найдите в датафрейме `final` героя, который произнёс эту фразу, скопируйте ссылку на страницу соответствующего актёра/актрисы.

Пример кода для выбора ячейки, которая находится на пересечении строки 1 и столбца `full_link`:

    final.loc[1, "full_link"]


Используя возможности библиотек `requests` и `BeautifulSoup`, извлеките со страницы актёра/актрисы дату его/её рождения и сохраните её в переменную `date` (чистый текст, тип `string`). Дата должна быть указана полностью, с годом в формате *год-месяц-день*. Для этого из разных фрагментов с датой на странице выберите походящий.

Примеры дат:
    
    1938-09-25
    1957-11-02

Пусть нашим героем будет Королева Флора.

In [20]:
### YOUR CODE HERE ###
# Выбираем актрису по роли (Флора)
actor_url = final.loc[final["role"].fillna("").str.contains("Флора"), "full_link"].iloc[0]
print("Страница актрисы:", actor_url)

Страница актрисы: https://www.kino-teatr.ru/kino/acter/w/sov/4484/bio/

In [21]:
# Скачиваем страницу актрисы
page = requests.get(actor_url)
soup = BeautifulSoup(page.text)
print(soup)

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta content="acter_works_right_top_sov_4484_desktop советские актрисы" name="keywords"/>
<meta content="Лидия Федосеева-Шукшина - актриса - биография - советские актрисы - Кино-Театр.Ру" name="description"/>
<title>Лидия Федосеева-Шукшина - актриса - биография - советские актрисы - Кино-Театр.Ру</title>
<link href="https://www.kino-teatr.ru/favicon.ico" rel="shortcut icon"/>
<link href="/static/css/style.css" rel="stylesheet" type="text/css"/>
<link href="/static/css/custom.css" rel="stylesheet" type="text/css"/>
<link href="/rss/rss.xml" rel="alternate" title="Кино-Театр.Ру RSS" type="application/rss+xml"/><meta content="443227169041895" property="og:app_id"/>
<meta content="Кино-Театр.Ру" property="og:site_name"/>
<meta content="Лидия Федосеева-Шукшина" property="og:title"/>
<meta content="https://www.kino-teatr.ru/kino/acter/w/sov/4484/bio/" property="og:url"/>
<meta content="https://www.kino-teatr.ru/acter/photo/4/8/4484/686438.jpg" property="og:image"/>
<meta content="Актриса" property="og:description"/>
<meta content="profile" property="og:type"/>
<meta content="summary_large_image" name="twitter:card"/>
<meta content="@KinoTeatr_Ru" name="twitter:site"/>
<meta content="@KinoTeatr_Ru" name="twitter:creator"/>
<meta content="Лидия Федосеева-Шукшина" name="twitter:title"/>
<meta content="Актриса" name="twitter:description"/>
<meta content="https://www.kino-teatr.ru/acter/photo/4/8/4484/686438.jpg" name="twitter:image"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<link href="/static/css/style_resp.css" rel="stylesheet" type="text/css"/>
<meta content="false" property="relap:article"/>
<style>
    .center_1200_to_320 { min-width: 320px; }
    @media all and ( min-width: 1200px ) {
        #all_body_block { background-color: #f9f9f9; width: 1200px!important; margin: 0 auto!important; }
        #top_line { min-height: 250px; }
        #top_space { display: none!important; }
        #header_block { z-index: 9999999999!important; }
        #menu_line { z-index: 1000000!important; }
        .content_block { z-index:100!important; }
        .center_1200_to_320 { position: relative; z-index: 11; }
    }
  </style> <script>
    // Проверяем поддержку flex
    var has_mobile = '1';
    var d = document.documentElement.style
    if (has_mobile && ! (('flexWrap' in d) || ('WebkitFlexWrap' in d) || ('msFlexWrap' in d)) && ! /bot|googlebot|yandexbot|crawler|spider|robot|crawling/i.test(navigator.userAgent)){
        var host = self.location.host;
        var path = self.location.pathname;
        var short_host = host.replace(/www\./ig, '');
        // Редиректим
        url = 'https://m.kino-teatr.ru' + path + '?noflex=1';
        self.location.href = url;
    }
  </script>
<link href="https://cdn.advertronic.io" rel="preconnect"/>
<link as="fetch" crossorigin="" href="https://cdn.advertronic.io/b/0bd1b4f6-f250-426d-9154-679f76f81279.json" rel="preload" type="application/json"/><script type="text/javascript">window.__SM_COUNTER_ID = 45130;</script></head>
<body><script async="" src="https://cdn.advertronic.io/j/s.js" type="module"></script>
<script>
    (window.advertronic = window.advertronic || {cmd:[]}).cmd.push({
        init:{userId: '0bd1b4f6-f250-426d-9154-679f76f81279'}
    });
</script><div style="position:absolute; top:-20px;">
<!--noindex-->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();
   for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
   k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(12718750, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        trackHash:true
   });
</script>
<noscript><div><img alt="" src="https://mc.yandex.ru/watch/12718750" style="position:absolute; left:-9999px;"/></div></noscript>
<!-- /Yandex.Metrika counter -->
<!--LiveInternet counter--><script>
new Image().src = "//counter.yadro.ru/hit;Cinemaentertainment?r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+""+screen.height+""+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,150))+
";"+Math.random();</script><!--/LiveInternet-->
<!--/noindex-->
</div><script type="text/javascript">
    var current_section = 'acter';
    var current_pagename = 'bio';

    window.addEventListener("DOMContentLoaded",function(event) {

      // Главное меню
      $("#nav > li > a").click(function () {
        if ($(this).attr('direct') == '1') {
          return true;
        }
        if ($(this).parent().hasClass('selected')) {
          $("#nav .selected div div").slideUp(50); $("#nav .selected").removeClass("selected");
        }
        else {
          $("#nav .selected div div").slideUp(50); $("#nav .selected").removeClass("selected");
          if ($(this).next(".subs").length) {
            $(this).parent().addClass("selected");
            $(this).next(".subs").children().slideDown(200);
          }
        };
        return false;
      });

      // Исправляем форматирование блоков
      fix_unformat_blocks();

    });
</script>
<!-- Шапка -->
<header>
<div id="header_block">
<div class="center_1200_to_320">
<div id="header_grid">
<!-- Кнопка меню и логотип для мобильного разрешения -->
<div id="mob_button_block"><div id="mob_button_icon"><a href="#" onclick="showMobMenu('mob_menu_block'); return false;"><img alt="Кино-Театр.Ру" id="mob_button_image" src="/static/images/menu_icon.svg"/></a></div><div id="mob_button_text" onclick="showMobMenu('mob_menu_block'); return false;">МЕНЮ</div></div>
<div id="mob_logo_block"><a href="/"><img alt="Кино-Театр.Ру" id="mob_logo_image" src="/static/images/kinoteatr_logo_mob.png"/></a></div>
<!-- Логотип -->
<div id="logo_block"><a href="https://www.kino-teatr.ru/"><img alt="Кино-Театр.Ру" id="logo_image" src="/static/images/kinoteatr_logo.png"/></a></div>
<!-- Поиск -->
<div id="search_block">
<form action="/search/" id="search_form_top" method="post">
<table id="search_block_table">
<tr>
<td id="search_input_place"><input autocomplete="off" id="search_input_top" name="text" type="text"/><div id="search_result_dropdown"></div></td>
<td id="search_button_place"><input alt="Найти" id="search_button" name="submit" src="/static/images/search_icon.svg" type="image"/></td>
</tr>
</table>
</form>
</div>
<!-- Спецпроект -->
<div id="special_block">
<a href="/go/1526/" target="_blank" title="Деконструкция «Предел риска»"><img alt="Деконструкция «Предел риска»" src="/media/379/image_9925.gif" width="175"/></a>
</div>
<!-- Авторизация -->
<div id="login_block">
<div id="login_button"><a href="/forum/auth/" id="login_button_text">войти</a></div>
</div>
</div>
</div>
</div>
</header>
<!-- Мобильное меню -->
<nav>
<div id="mob_menu_block">
<div class="mob_menu">
<ul id="mob_nav">
<li id="full_version_item"><a href="/switch/full/" rel="nofollow"><strong>Полная версия</strong></a></li>
<li><a href="/online/"><strong>Смотреть онлайн</strong></a></li>
<li><a href="/rating2/movie/ros/"><strong>Рейтинг фильмов</strong></a></li>
<li><a href="/rating3/movie/ros/series/"><strong>Рейтинг ожиданий</strong></a></li>
<li><a href="/kino/news/"><strong>Новости</strong></a></li>
<li><a href="/casting/info/"><strong>Кастинг</strong></a></li>
<li><a href="/kino/db/ros/acter/"><strong>Актёры</strong></a></li>
<li><a href="/kino/db/ros/movie/"><strong>Фильмы</strong></a></li>
<li><a href="/kino/db/director/"><strong>За кадром</strong></a></li>
<li><a href="/teatr/"><strong>Театр</strong></a></li>
<li><a href="/kino/person/"><strong>Интервью</strong></a></li>
<li><a href="/kino/art/pr/"><strong>Рецензии</strong></a></li>
<li><a href="/kino/art/kino/"><strong>История</strong></a></li>
<li><a href="/guest/"><strong>Гостевая книга</strong></a></li>
<li><a href="/forum/auth/" title="Вход на форум"><strong>Вход на форум</strong></a></li>
<li><a href="/forum/reg/" title="Регистрация на форуме"><strong>Регистрация на форуме</strong></a></li>
<li><a href="/forum/topics/" title="Свободные темы"><strong>Свободные темы</strong></a></li>
</ul>
</div>
</div>
</nav>
<!-- Основное меню -->
<nav>
<div id="menu_line">
<div class="center_1200_to_320">
<div id="menu_block">
<div class="menu">
<div class="menu_center">
<ul id="nav">
<li onclick="showMenu(this)"><a href="/kino/news/"><strong>Новости</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/blog/" title="Отчеты дозорных"><strong>Дозорные</strong></a></li>
<li><a href="/lifestyle/news/" title="Лайфстайл"><strong>Лайфстайл</strong></a></li>
<li><a href="/kino/news/" title="Новости кино"><strong>Новости кино</strong></a></li>
<li><a href="/teatr/news/" title="Новости театра"><strong>Новости театра</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="ym(12718750,'reachGoal','menu_casting'); showMenu(this);"><a href="/casting/info/" title="Кастинг"><strong>Кастинг</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/casting/info/" title="Общая информация"><strong>Общая информация</strong></a></li>
<li><a href="/casting/info/acter/" title="Информация для актёров"><strong>Информация для актёров</strong></a></li>
<li><a href="/casting/info/special/" title="Информация о спецучете"><strong>Информация о спецучете</strong></a></li>
<li><a href="/casting/photo/" title="Заказ портфолио"><strong>Заказ портфолио</strong></a></li>
<li><a href="/casting/" title="Поиск"><strong>Поиск</strong></a></li>
<li><a href="/casting/auth/" title="Вход для кастинг-директоров"><strong>Вход для кастинг-директоров</strong></a></li>
<!--<li><a href="/casting/office/" title="Вход для актёров"><strong>Личный кабинет актёра</strong></a></li>-->
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/db/ros/acter/"><strong>Актёры</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/kino/db/ros/acter/" title="Российские актеры"><strong>Российские актеры</strong></a></li>
<li><a href="/kino/db/sov/acter/" title="Советские актеры"><strong>Советские актеры</strong></a></li>
<li><a href="/kino/db/star/acter/" title="Знаменитости в кино"><strong>Знаменитости в кино</strong></a></li>
<li><a href="/kino/db/post/acter/" title="Актеры Ближнего Зарубежья"><strong>Актеры Ближнего Зарубежья</strong></a></li>
<li><a href="/kino/db/empire/acter/" title="Актеры Российской империи"><strong>Актеры Российской империи</strong></a></li>
<li><a href="/kino/db/hollywood/acter/" title="Голливудские актеры"><strong>Голливудские актеры</strong></a></li>
<li><a href="/kino/db/euro/acter/" title="Европейские актеры"><strong>Европейские актеры</strong></a></li>
<li><a href="/kino/db/asia/acter/" title="Азиатские актеры"><strong>Азиатские актеры</strong></a></li>
<li><a href="/kino/db/latin/acter/" title="Латиноамериканские актеры"><strong>Латиноамериканские актеры</strong></a></li>
<li><a href="/teatr/db/acter/" title="Актеры театра"><strong>Актеры театра</strong></a></li>
<li><a href="/kino/acter/group/veteran/" title="Участники Великой Отечественной войны"><strong>Участники ВОВ</strong></a></li>
<li><a href="/kino/acter/group/front/" title="Артисты фронтовых бригад"><strong>Артисты фронтовых бригад</strong></a></li>
<li><a href="/foto/" title="Фотографии актеров"><strong>Фотографии актеров</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/db/ros/movie/"><strong>Фильмы</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/afisha/" title="Афиша кино, новинки кинопроката"><strong>График кинопремьер</strong></a></li>
<li><a href="/online/" title="Смотреть фильмы и сериалы онлайн"><strong>Смотреть фильмы онлайн</strong></a></li>
<li><a href="/digital/" title="Цифровые премьеры, дата выхода"><strong>График цифровых премьер</strong></a></li>
<li><a href="/premieres/" title="ТВ премьеры, дата выхода"><strong>Премьеры ТВ</strong></a></li>
<li><a href="/rating2/movie/ros/" title="Рейтинг фильмов"><strong>Рейтинг фильмов</strong></a></li>
<li><a href="/rating3/movie/ros/series/" title="Рейтинг ожиданий"><strong>Рейтинг ожиданий</strong></a></li>
<li><a href="/kino/db/ros/movie/hud/" title="Российские фильмы"><strong>Российские фильмы</strong></a></li>
<li><a href="/kino/db/ros/movie/ser/" title="Российские сериалы"><strong>Российские сериалы</strong></a></li>
<li><a href="/kino/db/post/movie/" title="Фильмы и сериалы Ближнего Зарубежья"><strong>Фильмы Ближнего Зарубежья</strong></a></li>
<li><a href="/kino/db/sov/movie/" title="Советское кино"><strong>Советское кино</strong></a></li>
<li><a href="/kino/db/empire/movie/" title="Фильмы Российской империи"><strong>Фильмы Российской империи</strong></a></li>
<li><a href="/kino/db/hollywood/movie/" title="Голливудские фильмы и сериалы"><strong>Голливудские фильмы</strong></a></li>
<li><a href="/kino/db/euro/movie/" title="Европейское кино"><strong>Европейское кино</strong></a></li>
<li><a href="/kino/db/asia/movie/" title="Азиатское кино"><strong>Азиатское кино</strong></a></li>
<li><a href="/kino/db/latin/movie/" title="Латиноамериканские фильмы и сериалы"><strong>Латиноамериканские фильмы</strong></a></li>
<li><a href="/mult/db/movie/" title="Мультфильмы"><strong>Мультфильмы</strong></a></li>
<li><a href="/teatr/db/movie/" title="Фильмы-спектакли"><strong>Фильмы-спектакли</strong></a></li>
<li><a href="/short/db/movie/" title="Короткометражные фильмы"><strong>Короткометражные фильмы</strong></a></li>
<li><a href="/doc/db/movie/" title="Документальные фильмы"><strong>Документальные фильмы</strong></a></li>
<li><a href="/kino/db/prod/movie/" title="Фильмы в производстве"><strong>Фильмы в производстве</strong></a></li>
<li><a href="/kino/db/undone/movie/" title="Незавершенные фильмы"><strong>Незавершенные фильмы</strong></a></li>
<li><a href="/video/" title="Ролики фильмов"><strong>Ролики фильмов</strong></a></li>
<li><a href="/posters/" title="Постеры фильмов"><strong>Постеры фильмов</strong></a></li>
<li><a href="/kadr/" title="Кадры из фильмов"><strong>Кадры из фильмов</strong></a></li>
<li><a href="/tv/" title="Программа ТВ"><strong>Программа ТВ</strong></a></li>
<!--<li><a href="/kinoteatr/" title="Афиша кинотеатров, расписание сеансов"><strong>Кинотеатры, расписание</strong></a></li>-->
<li><a href="/box/" title="Кассовые сборы"><strong>Кассовые сборы</strong></a></li>
<li><a href="/unident/" title="Неопознанные кадры"><strong>Неопознанные кадры</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/db/director/"><strong>За кадром</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/kino/db/director/" title="Режиссеры"><strong>Режиссеры</strong></a></li>
<li><a href="/kino/db/screenwriter/" title="Сценаристы"><strong>Сценаристы</strong></a></li>
<li><a href="/kino/db/producer/" title="Продюсеры"><strong>Продюсеры</strong></a></li>
<li><a href="/kino/db/operator/" title="Операторы"><strong>Операторы</strong></a></li>
<li><a href="/kino/db/composer/" title="Композиторы"><strong>Композиторы</strong></a></li>
<li><a href="/kino/db/painter/" title="Художники-постановщики"><strong>Художники</strong></a></li>
<li><a href="/kino/db/stuntman/" title="Каскадеры"><strong>Каскадеры</strong></a></li>
<li><a href="/mult/db/director/" title="Режиссеры-мультипликаторы"><strong>Режиссеры-мультипликаторы</strong></a></li>
<li><a href="/mult/db/painter/" title="Художники-мультипликаторы"><strong>Художники-мультипликаторы</strong></a></li>
<li><a href="/kino/acter/group/operator/" title="Фронтовые кинооператоры"><strong>Фронтовые кинооператоры</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/teatr/"><strong>Театр</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/teatr/db/acter/" title="Актеры театра"><strong>Актеры театра</strong></a></li>
<li><a href="/teatr/db/movie/" title="Фильмы-спектакли"><strong>Фильмы-спектакли</strong></a></li>
<li><a href="/teatr/db/activist/" title="Театральные деятели"><strong>Театральные деятели</strong></a></li>
<li><a href="/teatr/moscow/" title="Театры Москвы"><strong>Театры Москвы и Подмосковья</strong></a></li>
<li><a href="/teatr/peterburg/" title="Театры Санкт-Петербурга"><strong>Театры Санкт-Петербурга</strong></a></li>
<li><a href="/teatr/russia/" title="Театры России"><strong>Театры России</strong></a></li>
<li><a href="/teatr/post/" title="Театры Ближнего Зарубежья"><strong>Театры Ближнего Зарубежья</strong></a></li>
<li><a href="/teatr/euro/" title="Театры Европы"><strong>Театры Европы</strong></a></li>
<li><a href="/teatr/old/" title="Театры прошлых лет"><strong>Театры прошлых лет</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/person/"><strong>Интервью</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/kino/person/" title="Киношные интервью"><strong>Киношные интервью</strong></a></li>
<li><a href="/teatr/person/" title="Театральные интервью"><strong>Театральные интервью</strong></a></li>
<li><a href="/lifestyle/person/" title="Лайфстайл"><strong>Лайфстайл</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/art/pr/"><strong>Рецензии</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/kino/art/pr/" title="Рецензии на фильмы"><strong>Рецензии на фильмы</strong></a></li>
<li><a href="/kino/art/serial/" title="Обзор сериалов"><strong>Обзор сериалов</strong></a></li>
<li><a href="/kino/art/tv/" title="Спутник телезрителя"><strong>Спутник телезрителя</strong></a></li>
<li><a href="/kino/art/animation/" title="Анимация"><strong>Анимация</strong></a></li>
<li><a href="/kino/art/video-review/" title="Видеообзоры"><strong>Видеообзоры</strong></a></li>
<li><a href="/kino/art/festival/" title="Фестивальная колонка"><strong>Фестивальная колонка</strong></a></li>
<li><a href="/kino/art/artkino/" title="Арт-хаус в кино"><strong>Арт-хаус в кино</strong></a></li>
<li><a href="/teatr/art/teatr/" title="Рецензии на спектакли"><strong>Рецензии на спектакли</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/kino/art/kino/"><strong>История</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/day/" title="В этот день родились"><strong>В этот день родились</strong></a></li>
<li><a href="/mourn/" title="В этот день ушли из жизни"><strong>В этот день ушли из жизни</strong></a></li>
<li><a href="/teatr/history/" title="Театральная хроника"><strong>Театральная хроника</strong></a></li>
<li><a href="/teatr/art/history/" title="История театра"><strong>История театра</strong></a></li>
<li><a href="/kino/history/" title="Хроника кино"><strong>Хроника кино</strong></a></li>
<li><a href="/kino/art/kino/" title="История кино"><strong>История кино</strong></a></li>
<li><a href="/box/history/" title="История кинопроката"><strong>История кинопроката</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/forum/topics/"><strong>Форум</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/forum/topics/" title="Свободные темы"><strong>Свободные темы</strong></a></li>
<li><a href="/forum/auth/" title="Вход на форум"><strong>Вход на форум</strong></a></li>
<li><a href="/forum/reg/" title="Регистрация на форуме"><strong>Регистрация на форуме</strong></a></li>
<li><a href="/forum/recovery/" title="Восстановление пароля"><strong>Восстановление пароля</strong></a></li>
</ul>
</div>
</div>
</li>
<li onclick="showMenu(this)"><a href="/guest/"><strong>Общение</strong></a>
<div class="subs">
<div>
<ul>
<li><a href="/guest/" title="Гостевая книга"><strong>Гостевая</strong></a></li>
<li><a href="/contact/" title="Контакты"><strong>Контакты</strong></a></li>
<li><a href="/team/" title="Команда"><strong>Команда</strong></a></li>

Так как на странице актрисы есть мета-тег itemprop="birthDate", указывающий на нужный контент - дату рождения (причем мы видим, что она сохранена именно в том формате, в котором она должна быть - полностью год-месяц-день), то используем его, причем дополнительное форматирование даты не требуется.

In [22]:
# Достаём дату рождения из meta-тега
try:
    date = soup.find("meta", attrs={"itemprop": "birthDate"})["content"]
except Exception:
    date = ""

print("Дата рождения актрисы:", date)

Дата рождения актрисы: 1938-09-25